# Generated by Django 2.2.23 on 2021-06-28 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_maps', '0002_add_layers_control_scale_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapsMarker',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_maps_mapsmarker', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('address', models.CharField(blank=True, help_text='Note: Latitude and longitude can be used to fine-tune the location.', max_length=255, verbose_name='Full address')),
                ('lat', models.FloatField(blank=True, help_text='Geographical latitude in degrees (e.g. "46.947973").', null=True, verbose_name='Latitude (lat)')),
                ('lng', models.FloatField(blank=True, help_text='Geographical longitude in degrees (e.g. "7.447446").', null=True, verbose_name='Longitude (lng)')),
                ('show_content', models.BooleanField(default=True, help_text='Display the info window when the map loads.', verbose_name='Show window')),
                ('info_content', models.TextField(blank=True, help_text='Will be displayed in the info window attached to the marker.', verbose_name='Info window content')),
                ('icon', filer.fields.image.FilerImageField(blank=True, help_text='A marker icon identifies a location on a map. A default icon is provided by default.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Icon')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='maps',
            name='content',
        ),
    ]
